### ISSUE TITLE
ServiceAccount can't be found when used as a subchart

### ISSUE THREAD

**Issue by chris922** [stackabletech/listener-operator#128]
### Affected version

23.11.0

### Current and expected behavior

I am using the listener-operator within a subchart that is named `stackable-operators`. Unfortunately I am getting the following error:
> error looking up service account stackable-system/stackable-operators-serviceaccount: serviceaccount "stackable-operators-serviceaccount" not found

I expect that using the listener-operator within a subchart is working.

### Possible solution

The listener-operator chart creates a ServiceAccount: https://github.com/stackabletech/listener-operator/blob/3ecc84029f3430e494bb0edb9c6e229df5ffa043/deploy/helm/listener-operator/templates/serviceaccount.yaml#L4-L6
The name is built like: `{{ include "operator.fullname" . }}-serviceaccount`

Having a look at the deployment this one is building the name out of a different pattern `{{ .Release.Name }}-serviceaccount`: https://github.com/stackabletech/listener-operator/blob/3ecc84029f3430e494bb0edb9c6e229df5ffa043/deploy/helm/listener-operator/templates/controller-deployment.yaml#L27

I think the `.Release.Name` should not be used here and the same approach should be used to derive the service account name.

Besides that I noticed that the deployment name is also derived from the `.Release.Name`, this should be changed as well. In other Helm charts the deployment names will not be derived from the release-name, see for example here: https://github.com/stackabletech/commons-operator/blob/main/deploy/helm/commons-operator/templates/deployment.yaml#L5

Right now my deployment is named `stackable-operators-controller-deployment` cause my main chart is named `stackable-operators` that contains the listener-operator as a subchart.

### Would you like to work on fixing this bug?

None

**Comment by nightkr** [comment]
Hey, looks like you're right, https://github.com/stackabletech/operator-templating/commit/2b73b32beb75a63600e50a962c50b473fda62021 wasn't replicated correctly here. We should also check whether secret-op has the same issue.
