### ISSUE TITLE
Investigate how we can accomodate external ip propagation in the listener operator

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/listener-operator#20]
In https://engineering.salesforce.com/hadoop-hbase-on-kubernetes-and-public-cloud-part-ii-e465f346da63/ SalesForce describe how they solve the issue of making kubernetes internal services externally accessible.

We should look into the possibility of accommodating this as an option in the listener operator.

**Comment by nightkr** [comment]
After discussing with @soenkeliebau it seems like this is a no-op for us for now, the exposed IP addresses/hostnames should be enough for our needs at the moment. We can always revisit this in the future, should the need arise.
