### ISSUE TITLE
Use `ClusterResources` to manage objects created by Listener controller

### ISSUE THREAD

**Issue by nightkr** [stackabletech/listener-operator#221]
From https://github.com/stackabletech/operator-rs/issues/861

**Comment by lfrancke** [comment]
Is this a new feature, an improvement, a bugfix or something else?

**Comment by nightkr** [comment]
Hm, I guess it's somewhere in between. It's a bugfix for the _general_ SDP expectation that orphans are cleaned up, but it's also new behaviour that would make it a feature? Hmm.
