### ISSUE TITLE
Docs don't mention `serviceType` values

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/listener-operator#71]
The docs should mention all possible service types or at least explain that these are the service Types from Kubernetes and link to their docs if possible.

Do we use a k8s-openapi field for ServiceType internally so that it'll automatically be updated if the values change?

**Comment by nightkr** [comment]
> Do we use a k8s-openapi field for ServiceType internally so that it'll automatically be updated if the values change?

No, because each supported `serviceType` takes some degree of special handling to manage correctly (for example: IP/port mapping is completely different for each supported service type).
